### ISSUE TITLE
图片超出背景

### ISSUE THREAD

**Issue by ccseer** [sivan/heti#106]
你好，
当图片分辨率过大时， 会超出显示区域。能否自动进行等比例缩放，如果超出大小就按照显示区域的最大可显示宽度显示？

![image](https://user-images.githubusercontent.com/15963166/209002904-a255e091-b03c-454e-ab24-50e61c073fdb.png)

**Comment by sivan** [comment]
好的，下次更新版本时会加上。可以临时增加下面的样式修复：
```css
.heti img {
  max-width: 100%;
  height: auto;
}
```
