### ISSUE TITLE
使用了heti样式后，文字无法居中

### ISSUE THREAD

**Issue by YangguangZhou** [sivan/heti#108]
截图：
![屏幕截图 2023-02-10 224205](https://user-images.githubusercontent.com/61733195/218119515-811ace78-71ca-4b8d-b01e-3f474c961f8f.jpg)

样式代码：
```css
.blink {
    position: fixed;
    height: 100%;
    width: 100%;
    text-align: center;
    display: flex;
    display: -webkit-flex;
    align-items: center;
    line-height: 30px;
    justify-content: center;
    animation: blink 3s linear infinite;
    -webkit-animation: blink 3s linear infinite;
    -moz-animation: blink 3s linear infinite;
    -ms-animation: blink 3s linear infinite;
    -o-animation: blink 3s linear infinite;
}
```
