### ISSUE TITLE
是否有办法仅使用 autospacing 但是不应用 heti 类样式的方法呢？

### ISSUE THREAD

**Issue by bluepikachu** [sivan/heti#119]
你好，我的博客有一套自己写好的 markdown 样式，现在试用 autospacing 必须使用 .heti 类，这会导致我的样式被覆盖。

我想了解是否有仅使用 autospacing 功能而不使用 heti 类的方式？

**Comment by sivan** [comment]
不引用`heti.min.css`，然后参考`lib/helpers/_add-on.scss`在你自己的样式里单独定义一下试试？
``` scss
.heti {
  heti-spacing {
    display: inline;
  }

  .heti-spacing-start {
    margin-inline-end: 0.25em;
  }

  .heti-spacing-end {
    margin-inline-start: 0.25em;
  }

  heti-adjacent {
    display: inline;
  }

  .heti-adjacent-half {
    margin-inline-end: -0.5em;
  }

  .heti-adjacent-quarter {
    margin-inline-end: -0.25em;
  }
}
```
