### ISSUE TITLE
[Bug] 楷体显示为宋体

### ISSUE THREAD

**Issue by XieJiSS** [sivan/heti#72]
目前楷体常规字重的定义如下：

```css
@font-face {
  font-family: "Heti Kai";
  src: local("Kaiti SC Regular"), local("Kaiti TC Regular"), local("BiauKai");
}
```

whatfontis.com 显示前两个字体来自 iOS，第三个字体来自 MacOS。在我的电脑（Windows 10）上没有发现这三个字体。

我目前的解决方案是：把楷体的 `@font-face` 修改为

```css
@font-face {
  font-family: "Heti Kai";
  src: local("Kaiti SC Regular"), local("Kaiti TC Regular"), local("STKaiti"), local("Kaiti"), local("BiauKai");
}
```

即可。其中 `STKaiti` 是华文楷体（`C:\Windows\Fonts\STKaiti.ttf`），来自 Office；`Kaiti` 的字体来源为 Windows 自带的字体库中的「楷体 常规」（`C:\Windows\Fonts\SimKai.ttf`）。

这里的问题是：`STKaiti` 和 `Kaiti` 的字重比较单一，二者的 `600` 和 `800` 字重显示效果完全一样。

如果作者认为这个更改合理，我可以提供 PR。
